name: Docker Builds, tags and pushes an image to DockerHub

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'pa.*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  docker-build-push:
    name: build-push-postgres-backup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          dockerfile: ./build/postgres-backup/Dockerfile
          username: ${{ secrets.DOCKER_HUB_USER  }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD  }}
          repository: proagenda2030/support_postgres_backup
          tag_with_ref: true
          tags: latest
